### PR TITLE
fix: package transition

### LINKED ISSUE #519: [BE] MCP search doesn't work correct for API operation search
### Describe the bug

to check MCP search please add prefix "__"

### To Reproduce

1. Navigate to the existing package
2. Execute move package
3. Chose any API operation from moved package and copy its name
4. Execute MCP search in Global search field (add prefix "__")

**ER: API operation was found
AR: API operation was NOT found**

### Version

Backend v. refs/tags/1.13.0.4d62957
Frontend v. 3.3.0
API Processor v. 5.0.0

### Logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by karpov-aleksandr**

### CODE REVIEW

File: qubership-apihub-service/migration/service/SoftMigrations.go [hunk 1]
```diff
@@ -1,17 +1,21 @@
...
 
 	"github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/metrics"
 	"github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/utils"
+	"github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/view"
 	"github.com/go-pg/pg/v10"
 	log "github.com/sirupsen/logrus"
 )
 
 const typeAndTitleMigrationVersion = 22
+const transitionRefsMigrationVersion = 29
```
Comment (viacheslav-lunev) [inline qubership-apihub-service/migration/service/SoftMigrations.go]: please update to 30

**Comment by karpov-aleksandr** [comment]
Tests run: https://github.com/Netcracker/qubership-apihub/actions/runs/22895066027
Newman tests are completed successfully. Failed Playwright tests are related to qubership-api-linter-service.

**Review by viacheslav-lunev — APPROVED** [review]
